title: Portfolio
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: false
nav_enabled: true
nav_sort: case_insensitive

nav_error_report: true

just_the_docs:
  auxiliary_stylesheets:
    - "/assets/css/custom.css"
